# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
