# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_blurb_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blurb',
            name='user',
        ),
    ]
