# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNASeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sequence', models.CharField(max_length=2000)),
            ],
        ),
    ]
