# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsensusSequence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RCSequence',
        ),
    ]
